name: Packer build


on:
  push:
    branches: [ main ]
jobs:
  build:
    name: packer workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        artifact-name: CSYE-6225-ORG/webservice-${{github.run_number}}.zip
    - name: Building Zip File
      run: |
        mkdir codedeploy_artifact1
        zip -r csye6225-webapp-${{ github.sha }} . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json" "packer/*"
        mv csye6225-webapp-${{ github.sha }}.zip codedeploy_artifact
    - name: Upload to S3
      run: |
        aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}
    - name: CodeDeploy API call
      run: |
        output=$(aws deploy create-deployment \
          --application-name ${{secrets.CODEDEPLOY_APPLICATION_NAME}} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{secrets.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} \
          --description "CSYE - CodeDeploy" \
          --s3-location bucket=${{secrets.S3_CODEDEPLOY_BUCKET}},key=csye6225-webapp-${{ github.sha }}.zip,bundleType=zip \
          --region ${{secrets.AWS_REGION}} \
          --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $dId